/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Arbol;
import Conexion.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JComboBox;


/**
 *
 * @author Pierre
 */
public class SugerenciaDePeliculas extends javax.swing.JFrame {
    private List<Pelicula> peliculas;

    /**
     * Creates new form NewJFrame
     */
    public SugerenciaDePeliculas() {
        initComponents();
        cargarDatosDesdeBD();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxGenero = new javax.swing.JComboBox<>();
        cbxClasificacion = new javax.swing.JComboBox<>();
        cbxDuracion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Genero");

        jLabel2.setText("Clasificacion");

        jLabel3.setText("Duracion");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnBuscar.setText("Buscar Recomendaciones");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("RECOMENDACION DE PELICULAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxDuracion, 0, 137, Short.MAX_VALUE)
                            .addComponent(cbxClasificacion, 0, 137, Short.MAX_VALUE)
                            .addComponent(cbxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatosDesdeBD() {
        // Use the CargarDatosDesdeBD class to load movie data from the database
        peliculas = CargarDatosDesdeBD.cargarPeliculasDesdeBD();

        // Populate the genero JComboBox with unique genres
        cargarGeneros();
    }
private boolean existeItemEnComboBox(JComboBox comboBox, String item) {
    for (int i = 0; i < comboBox.getItemCount(); i++) {
        if (comboBox.getItemAt(i).equals(item)) {
            return true;
        }
    }
    return false;
}
    private void cargarGeneros() {
    cbxGenero.removeAllItems();
    for (Pelicula pelicula : peliculas) {
        if (!existeItemEnComboBox(cbxGenero, pelicula.getGenero())) {
            cbxGenero.addItem(pelicula.getGenero());
        }
    }
    

    // Add ActionListener to cbxGenero to update cbxClasificacion
    cbxGenero.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Get the selected genre
            String selectedGenero = (String) cbxGenero.getSelectedItem();

            // Update the cbxClasificacion based on the selected genre
            cargarClasificaciones(selectedGenero);

            // Clear cbxDuracion and cbxDirector
            cbxDuracion.removeAllItems();
        }
    });
}

private void cargarClasificaciones(String generoSeleccionado) {
    cbxClasificacion.removeAllItems();
    for (Pelicula pelicula : peliculas) {
        if (pelicula.getGenero().equals(generoSeleccionado)) {
            cbxClasificacion.addItem(pelicula.getClasificacionEdad());
        }
    }

    // Add ActionListener to cbxClasificacion to update cbxDuracion
    cbxClasificacion.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Get the selected clasificacion
            String selectedClasificacion = (String) cbxClasificacion.getSelectedItem();

            // Update the cbxDuracion based on the selected clasificacion
            cargarDuraciones(generoSeleccionado, selectedClasificacion);

            // Clear cbxDirector
        }
    });
}

private void cargarDuraciones(String generoSeleccionado, String clasificacionSeleccionada) {
    cbxDuracion.removeAllItems();
    for (Pelicula pelicula : peliculas) {
        if (pelicula.getGenero().equals(generoSeleccionado) && pelicula.getClasificacionEdad().equals(clasificacionSeleccionada)) {
            cbxDuracion.addItem(String.valueOf(pelicula.getDuracion()));
        }
    }

    // Add ActionListener to cbxDuracion to update cbxDirector
    cbxDuracion.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Get the selected duracion
            String selectedDuracion = (String) cbxDuracion.getSelectedItem();

            // Update the cbxDirector based on the selected duracion
        }
    });
}



    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String generoSeleccionado = (String) cbxGenero.getSelectedItem();
        String clasificacionSeleccionada = (String) cbxClasificacion.getSelectedItem();
        String duracionSeleccionada = (String) cbxDuracion.getSelectedItem();

        // Fetch and display movie recommendations based on selected criteria
        mostrarRecomendaciones(generoSeleccionado, clasificacionSeleccionada, duracionSeleccionada);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void mostrarRecomendaciones(String genero, String clasificacion, String duracion) {
        StringBuilder recomendaciones = new StringBuilder();
        for (Pelicula pelicula : peliculas) {
            if (pelicula.getGenero().equals(genero) && pelicula.getClasificacionEdad().equals(clasificacion)
                    && String.valueOf(pelicula.getDuracion()).equals(duracion)) {
                recomendaciones.append("Título: ").append(pelicula.getTitulo()).append(", Director: ").append(pelicula.getDirector()).append("\n");
            }
        }
        jTextArea1.setText(recomendaciones.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SugerenciaDePeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SugerenciaDePeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SugerenciaDePeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SugerenciaDePeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SugerenciaDePeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbxClasificacion;
    private javax.swing.JComboBox<String> cbxDuracion;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
